### ISSUE TITLE
GPUImage 1 vs GPUImage 2? Performance differences?

### ISSUE THREAD

**Issue by travisweerts** [BradLarson/GPUImage2#12]
Hey Brad, super excited about this new release. Great work... You inspire.

I was wondering if you had done any metrics on the new version versus the old? Are there significant performance increases?

**Comment by BradLarson** [comment]
In general, the per-frame processing benchmarks are pretty much the same right now. 

The new framework is slightly slower on iOS in movie recording, raw data capture, and image capture, which at present don't use the iOS texture caches in the new framework. That should be fixed soon.

Point extraction from the Harris corner detector and others is slower on unoptimized builds, but that's because you don't want to do benchmarking against -Onone builds for Swift. The -O level of optimization takes care of that, and brings performance close to the raw C I used in the old stuff without the dangers and awkardness of the raw pointers you had to handle.

The Mac camera in the new framework is significantly faster, since it now uses YUV capture / GPU conversion to RGB instead of BGRA capture. I'll be adding the new (in 10.11) texture caches on the Mac to further speed this up.

The new framework is way faster at anything that uses large-area Gaussian or box blurs. It now does these in nearly constant time with increasing radii beyond 8 pixels, due to the use of automatic downsampling and upsampling. It's the difference between a frame taking >200 ms to process on an iPhone 4S in the old version and only 8 ms in the new framework. The quality of these large-area blurs should also be improved.

I will be using VBOs to cache vertex data, which should lead to a small but noticeable reduction in CPU overhead across the entire framework.

I also am attempting to split output video frames into Y and UV planes for movie recording, which I think will lead to a large improvement in movie recording performance.

Overall, the framework should be faster in every part than the old framework, and much faster in some, but I need to get everything operational first before I apply many optimizations.

**Comment by travisweerts** [comment]
Brad, thanks for the update! Sounds like you get your work cut out for ya! Excited about the future of GPUImage 2. And love the new "masking" feature... thanx again
