### ISSUE TITLE
Record Video from PictureInput ?

### ISSUE THREAD

**Issue by omarojo** [BradLarson/GPUImage2#177]
Does PictureInput works with MovieOutPut ?
my entire filterchain works when recording using the camera as input.. 
but if I change the camera with a PictureInput to record a video from a Still, it records nothings.
actually the `newFramebufferAvailable` method inside MovieOutput never gets called.

camera->someFilter->movieOutPut      (works)
pictureInput->someFilter->movieOutPut (doesnt work, doesnt crash either)

**Comment by BradLarson** [comment]
No, it does not. A PictureInput is a still image that does not change over time. You can't construct a movie from it, because a movie requires a feed of image frames that change over time.

**Comment by omarojo** [comment]
but what if I call  processImage() with a timer ? Im doing that with a timer and or slider.. to change the filter values.. and get the renderview to update properly..  working fairly well with some crashes. 

isnt processImage() sending and updated frame thru the pipeline ?

**Comment by fungkwokpan** [comment]
I had a timer sending a changing uniform to custom filters and I needed to record a video although it originates as a PictureInput. To resolve this, I changed the newFramebufferAvailable method. Basically it doesn't record because of this line -

`guard let frameTime = framebuffer.timingStyle.timestamp?.asCMTime else { return }`

since the static image framebuffer from PictureInput does not come with a CMTime. So you just need to create your own CMTime for your frameTime e.g. CMTimeMake(0, 30) (which simply means the 0 mark at 30 frames per second in this case), and increment the CMTime value for every call. 

seems like the newFramebufferAvailable is called even if you don't call processFrame() so you need a way to tell movieOutput to stop recording the frames when the animation stop, before movieOutput.finishRecording() is called. otherwise you will be stuck with a number of static frames at the end

Hope this helps!
