### ISSUE TITLE
Is it possible to use a r200 or r300 realsense camera?

### ISSUE THREAD

**Issue by jandolina** [BradLarson/GPUImage2#186]
Hello,
I just stumbled into the R200 and R300 cameras by Intel. They provide depth information from some sort of laser scanner. Have any of you gotten one of these to work with GPUImage?

Thanks!

**Comment by BradLarson** [comment]
I've actually worked with the precursor cameras for these models. The color camera input portion shows up as a USB Vision Camera compliant camera, so that appears to AV Foundation just like any other camera. You can use GPUImage to capture and manipulate the video frames you get from that.

However, the depth information (which is the result of an IR time-of-flight camera) is provided in a proprietary format that is not surfaced to AV Foundation. You'd need some means of extracting that information, and the last time I'd checked they only had Windows support for this. You could potentially build a custom data input source for feeding this information into GPUImage (I've done this for other cameras not supported by AV Foundation), but it will take some work.

**Comment by jandolina** [comment]
Thank you!
