### ISSUE TITLE
SimpleVideoRecorder not recording

### ISSUE THREAD

**Issue by chnbr** [BradLarson/GPUImage2#40]
Hi,

I got your simplevideorecorder example working (checkout date 2016-07-05). Two things:

1. I think it should read
                dispatch_async(dispatch_get_main_queue()) {
                  (sender as! UIButton).titleLabel?.text = "Stop"
                }
The dispatch is missing. That resulted on my iPhone5 to the effect that the label did not change after starting recording.

2. I was not able to record anything. According to the frame times it looks like AssetWriter would write due to the increase in work load. However after stopping the recording no file seems to be written. At least I could not find something in the Photos-App. BTW: The callback finishRecording() gets executed.

Any ideas ?

Thanks for your extremely good work

Chris

**Comment by BradLarson** [comment]
capture() should only ever be called on the main thread, since it is triggered by the UI. You shouldn't need a dispatch on the main queue there. You do in the case of the recording completion callback, but not here.

Nothing is written in the photo library, it's just written within the application's Documents directory. If you grab the application bundle, you'll see the video there. I didn't want to add the code to copy this into the photo library just because I wanted this to be as simple an example as possible.
