### ISSUE TITLE
Will this use Metal?

### ISSUE THREAD

**Issue by pjebs** [BradLarson/GPUImage2#5]
There is another project: https://github.com/wangjwchn/MetalAcc

It claims to be based on CPUImage1 but "using Metal and written in Swift".
Will there be more advantages using Metal?

**Comment by BradLarson** [comment]
Probably not. One of the driving factors in rewriting the framework in Swift was to allow for it to work on platforms outside of Mac and iOS. In particular, I want this to run on desktop and embedded Linux devices. Metal is a very interesting technology, but it doesn't exist on those other platforms.

There are a few places where Metal might make building things internally a little easier, but for performance I don't think it would have that large an impact. It really shines for situations where you have a ton of draw calls or state changes, and want to be able to update various parts of a scene in a multithreaded manner. There's only a single draw call in general for each rendered frame in this framework, and I even cache shader programs and uniform values to further minimize state changes. Image frames need to be processed in sequence, so simple queue-based multithreading is all I need.

That's a fascinating project, and I'd be interested in testing it vs. this, but the small performance advantages it might give are outweighed by the reduction in platform support.

**Comment by erickingxu** [comment]
Hi @pjebs and @BradLarson ,
Thanks for Brad's work for GPUImage, and I try some Metal API for my recently work, I found it was some tips for newer in Image processing .
Metal is low level api to Opengles, i used it because it computing some image works like gaussian and face transform is much easier and faster with its multithreads. 
On an other hand, its rendering pass is designed better in 3D. 
Especially, you can biltCommand to copy bytes easier between textures and buffers with a better speed.
So I try to write a easy Metal framework like GPUImage design for this, you can refer to it in GitHub:
https://github.com/erickingxu/MetalImage

**Comment by mahdidham** [comment]
Is it possible to merge Metal API project like [this project](https://github.com/christopherhelf/iOS-Metal-HaarCascade) with this Framework? I want to detect features using ShiTomasi feature detector inside the [haar-cascade](https://github.com/christopherhelf/iOS-Metal-HaarCascade)'s rectangle that using Metal API. Thanks @BradLarson

**Comment by dstimm-gpfw** [comment]
I think it is time to support Metal since OpenGL is deprecated on iOS and macOS.

**Comment by BradLarson** [comment]
This is being addressed in issue #250 , as well as here:

https://github.com/BradLarson/GPUImage3
