### ISSUE TITLE
How do you use crop and what is type size in swift 3. 

### ISSUE THREAD

**Issue by lws803** [BradLarson/GPUImage2#76]
I'm using this as a sample code: 

let toonFilter = SmoothToonFilter()
let testImage = UIImage(named:"WID-small.jpg")!
let pictureInput = PictureInput(image:testImage)
let pictureOutput = PictureOutput()
pictureOutput.imageAvailableCallback = {image in
    // Do something with image
}
pictureInput --> toonFilter --> pictureOutput
pictureInput.processImage(synchronously:true)

because I need to continuously change and display different filtered images on the image view. Do I create a crop function as such? 

let cropFunction = Crop().cropSizeInPixels ? but if so how do I apply type size? 

Thanks

**Comment by BradLarson** [comment]
Crops are done via the Crop operation. Crop isn't a function, it's just a BasicOperation subclass like many other filters and operations. To use it, create a Crop instance and set its cropSizeInPixels property to the size you wish to crop. If you don't want the crop to be centered on the frame, you can set locationOfCropInPixels to place the crop anywhere you want in the frame.

Once you have the Crop instantiated and set up, insert it into your image processing pipeline via -->, like any other operation. I might recommend placing it as early as it makes sense, because that will cut down on unnecessary pixel processing from pixels that will ultimately be rejected anyways.
