### ISSUE TITLE
Camera change filter live.

### ISSUE THREAD

**Issue by ronysteel** [BradLarson/GPUImage2#85]
Hi, I trying to change camera filter, but nothing is happening...
My code:
        camera?.removeAllTargets()
        let filter = SketchFilter()
        camera! --> filter --> renderView
        camera?.startCapture()

Please, say me what I'm doing not correctly...

**Comment by nateemma** [comment]
In theory that should work. You can try adding camera?.stopCapture() at the beginning and see if that works. 
Also, was there a previous filter active? If so, you need to remove the targets from that (because it is linked to the renderView). 
How are camera and renderView defined and initialised? If renderView is defined as RenderView? then you should be using renderView! (add the !) You should probably check that camera != nil and that the renderView frame size has been set appropriately, though you would see an error if it was not set at all

Hope that helps

**Comment by zubco** [comment]
I have tried it also, it's not working. @nateemma even if you send camera?.stopCapture()

**Comment by BradLarson** [comment]
Remember to also use removeAllTargets() on any filter that's pointing to the renderView (as you can see the Mac FilterShowcase doing), or the old filter will remain locked on the renderView and you may not be able to add another as a target to it.

Look at your console logs for a debug build. You're most likely seeing warnings that you're attempting to add something as a target to a single-input view that can't take another target.

Again, the Mac FilterShowcase switches between multiple filters with the same camera and renderView, and can be used as an example of this.

**Comment by zubco** [comment]
Yeah, make sens :)
@ronysteel by adding smth like:
`previousFilter.removeAllTargets()`
before setting new filter, should resolve your issue.

**Comment by ronysteel** [comment]
@BradLarson 
@zubco 
@nateemma 
Thank you verry much!
