### ISSUE TITLE
Auto resize without processing

### ISSUE THREAD

**Issue by plougy** [BradLarson/GPUImage2#88]
I would test GPUImage to slice a large image (20880 x 1280) to a small image (720 x 1280) but without params I get an image automatically resized. That's possible to disable this behavior?

```swift
let image = UIImage(named:"test")!
// size: (20880.0, 1280.0)
        
let pictureInput = PictureInput(image: image)
let pictureOutput = PictureOutput()
pictureOutput.imageAvailableCallback = { image in
    // size: (4096.0, 251.0)
}
pictureInput --> pictureOutput
pictureInput.processImage(synchronously: true)
```

Thank you 😉

**Comment by zubco** [comment]
@plougy yes, this source image resize is intentional:
`public func sizeThatFitsWithinATextureForSize(_ size:Size) -> Size {
        let maxTextureSize = Float(self.maximumTextureSizeForThisDevice)
       ...
    }
...

public var maximumTextureSizeForThisDevice:GLint {get { return _maximumTextureSizeForThisDevice } }
    private lazy var _maximumTextureSizeForThisDevice:GLint = {
        return self.openGLDeviceSettingForOption(GL_MAX_TEXTURE_SIZE)
    }()
`
Where OpenGLES - GL_MAX_TEXTURE_SIZE, will represent your device hardware capabilities (amount of texture memory available on video chip).

If you however still want to work with original size images, you should look for some kind of image - tiles split technics..
Cheers ;)

**Comment by plougy** [comment]
@zubco thanks for your support.

What did you means by a tiles split technics?

**Comment by zubco** [comment]
@plougy I mean, 
1. split the image in multiple chunks with manageable size
2. process them
3. combine processed chunks back in one image
Result: you have your "very large" image processed. 

This is ideea in general for image processing for a large image.

!!!
Sorry, that I missed your original purpose when you get your problem.

If you just want to split a very large image, try to do it with UIGraphics (you should find easy an example with google).
In GPUImage2 framework there are no solution implemented for this kind of problems, yet.

**Comment by plougy** [comment]
I wanted only split the image without process for the moment.

I tested several things about UIGraphic but I get all the time a memory leak on `UIGraphicsGetImageFromCurrentImageContext` after 29 slice different and repeat 3 times... 

Thanks for your help but I think I'm on the wrong way 😟

**Comment by BradLarson** [comment]
As zubco said, extremely large images are difficult to work with in GPUImage due to the maximum texture size supported by the GPU. All frames and intermediate steps are held in textures in GPUImage, so you generally can't handle images greater than 4096x4096 on modern devices.

The image would have to be sliced into smaller pieces before being uploaded into a texture, something that I don't currently have code to do. You'd also have to make these slices just a bit larger than you'd actually need, in order to avoid edge effects. This is something I've had on the to-do list for four years: https://github.com/BradLarson/GPUImage/issues/42 , but haven't had the time to implement.

**Comment by plougy** [comment]
Thank you both for your help.

We're working to change our processing in the goal avoid to get an very large image.
